### ISSUE TITLE
Implement favicon from Zinix

### ISSUE THREAD

**Issue by Unisergius** [onelikeandidie/meetballs.org#4]
source https://discord.com/channels/502126962328993802/502405736085585920/1192206162318340217

**Comment by onelikeandidie** [comment]
Although I do agree the website needs a favicon, I think it needs some adjusting later. I'll add it for now but maybe we could do a contest to get some of the UX devs doing something :).

![The favicon by Zinix](https://cdn.discordapp.com/attachments/502405736085585920/1192206162133799002/meetballfav.png?ex=65b17603&is=659f0103&hm=7689391f07d0215989f373d6b1d24412b6ddfab9aae97e08123d459d42d74921&)

**Comment by Unisergius** [comment]
I do agree with the contest later this year, but for now this serves perfectly since it was a pretty cool contribution.

**Comment by onelikeandidie** [comment]
Closed with #11
